kumuluzee:
  name: e-scooter-orders
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8086
    http:
      port: 8086
  datasources:
    - jndi-name: jdbc/EscooterOrdersDS
      connection-url: jdbc:postgresql://127.0.0.1:5432/escooterorders
      username: dbuser
      password: postgres
      max-pool-size: 20